"""empty message

Revision ID: 0e133938fffa
Revises: 
Create Date: 2025-10-25 14:37:36.933373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e133938fffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('ai_confidence', sa.Integer(), nullable=False),
    sa.Column('reportedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imganalyzed', sa.Integer(), nullable=False),
    sa.Column('wastedected', sa.Integer(), nullable=False),
    sa.Column('avgconfidence', sa.Integer(), nullable=False),
    sa.Column('detectionrate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pwd', sa.String(length=256), nullable=False),
    sa.Column('admin', sa.String(length=64), nullable=False),
    sa.Column('datejoined', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('statistics')
    op.drop_table('reports')
    op.drop_table('cameras')
    # ### end Alembic commands ###
